### PR TITLE
Some browsers in private mode still have localStorage but it errors when you try to use it

### PR DESCRIPTION
**Pull request by mikebaldry**

### CODE REVIEW

**Comment by morris** [comment]
Awesome catch. Can you explain how to reproduce in detail (i.e. which browser etc.)? I'd rather just try/catch the line(s) that might throw instead of doing a separate check. Thanks!

**Comment by mikebaldry** [comment]
I believe one instance is safari in private mode. The property exists on window but raises when you try and access it

**Comment by morris** [comment]
It seems Safari sets the localStorage quota to 0 in private mode which results in quota exceeded errors when writing to the storage. Also according to [this](http://chrisberkhout.com/blog/localstorage-errors/) no other errors are possible in any browser.

I'm unsure whether we should silently ignore them because users might want to know when quota (0 or otherwise) is exceeded. Also, since the XHR is async and the exception is thrown in the last statement of the ready state change, the error will just be logged to console and everything else proceeds normally. So right now, nothing breaks (I'll add tests for that) - we just have to decide whether to catch and ignore, catch and log, or just let it throw.

**Comment by morris** [comment]
On a second thought, there's a scenario where getting the Typekit from localStorage works, but caching the next Typekit fails because the quota would be exceeded. That would leave the cached Typekit in use forever.

**Pull request closed without merging**
